### ISSUE TITLE
A null report.

### ISSUE THREAD

**Issue by jerryzooyoyo** [EmreTr1/GameSelector#6]
無法處理事件 'pocketmine\event\inventory\InventoryTransactionEvent' 至 'GameSelector v'：Call to a member function getName() on null 在 GameSelector\Main 上

Error: "Call to a member function getName() on null" (EXCEPTION) in "/plugins/GameSelector/src/GameSelector/Main" at line 195

### Although this doesn't have any problem in game, but hope you could fix it.

**Comment by EmreTr1** [comment]
now fixed?
